// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Permission struct {
	ID   int32
	Name string
}

type Role struct {
	ID   int32
	Name string
}

type RolesPermission struct {
	RoleID       int32
	PermissionID int32
}

type User struct {
	ID        int32
	Name      string
	Password  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UsersRole struct {
	UserID int32
	RoleID int32
}
