package database

import (
	"context"
	"log"

	models "project-sqlc/internal/db/models"

	"github.com/jackc/pgx/v5/pgxpool"
)

type Database struct {
	Pool  *pgxpool.Pool
	Query *models.Queries
}

func NewDatabase(connStr string) *Database {
	// this only create pgxpool struct, you may need to ping the database to
	// grab a connection and check availability
	log.Println("Connecting to database...", connStr)
	pool, err := pgxpool.New(context.Background(), connStr)
	if err != nil {
		log.Fatal(err)
	}

	// this is generated by sqlc cli
	query := models.New(pool)

	database := Database{
		Pool:  pool,
		Query: query,
	}
	return &database
}
