name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: log env variables
        run: |
          echo $SECRET_KEY
          echo $REFRESH_SECRET_KEY

      - name: run
        run: make run
