name: Deploy to Railway

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Goose
        uses: mscno/setup-goose@v1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test ./... -v

      - name: Add .env file
        run: |
          cp .env.example .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DRIVER=${{ secrets.DRIVER }}" >> .env
          echo "MIGRATIONS_DIR=${{ secrets.MIGRATIONS_DIR }}" >> .env

      - name: Run migrations
        run: make migrate

      - name: Deploy Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE }}
